# Generated by Django 2.2.28 on 2022-10-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_admin', '0003_agreedengagement_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHourRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('ongoing', models.BooleanField(default=False)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.AgreedEngagement')),
            ],
        ),
    ]
