# Generated by Django 2.2.28 on 2022-10-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshourrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
