# Generated by Django 2.2.28 on 2022-11-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_site', '0003_expertrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshourrequest',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
