# Generated by Django 2.2.28 on 2022-11-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_site', '0005_auto_20221110_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshourrequest',
            name='ongoing',
        ),
        migrations.AddField(
            model_name='businesshourrequest',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
