# Generated by Django 2.2.28 on 2022-11-10 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_site', '0006_auto_20221110_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshourrequest',
            name='request_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_user_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
