# Generated by Django 2.2.28 on 2022-07-14 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Expert', 'Expert'), ('Business', 'Business')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='user_resume/')),
                ('hourly_rate', models.FloatField()),
                ('expert_bio', models.TextField(max_length=800)),
                ('weekly_availability', models.CharField(choices=[('10-20 hours per week', '10-20 hours per week'), ('30-40 hours per week', '30-40 hours per week'), ('40+ hours per week', '40+ hours per week')], max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('primary_expertise', models.ManyToManyField(related_name='primary', to='users.UserExpertise')),
                ('secondary_expertise', models.ManyToManyField(related_name='secondary', to='users.UserExpertise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vertical_section', models.ManyToManyField(related_name='vertical', to='users.UserExpertise')),
            ],
        ),
    ]
