# Generated by Django 2.2.28 on 2022-08-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220804_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vertical_section',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekly_availability',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_availability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_expertise',
            field=models.ManyToManyField(blank=True, related_name='primary', to='users.UserExpertise'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondary_expertise',
            field=models.ManyToManyField(blank=True, related_name='secondary', to='users.UserExpertise'),
        ),
    ]
