# Generated by Django 2.2.28 on 2022-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220810_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Expert', 'Expert'), ('Business', 'Business'), ('Admin', 'Admin')], max_length=10, null=True),
        ),
    ]
