# Generated by Django 2.2.28 on 2022-08-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='business_logo/'),
        ),
    ]
