# Generated by Django 2.2.28 on 2022-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_upselltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
