# Generated by Django 2.2.28 on 2022-09-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_businessprofile_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
