# Generated by Django 2.2.28 on 2022-10-05 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220916_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexpertise',
            old_name='name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='primary_expertise',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secondary_expertise',
        ),
        migrations.AddField(
            model_name='userexpertise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_expertise', to=settings.AUTH_USER_MODEL),
        ),
    ]
