# Generated by Django 2.2.28 on 2022-10-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20221005_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexpertise',
            name='user',
        ),
        migrations.AddField(
            model_name='userexpertise',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='users.Profile'),
        ),
    ]
