# Generated by Django 2.2.28 on 2022-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_appliedexperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_email',
            field=models.BooleanField(default=True),
        ),
    ]
