# Generated by Django 2.2.28 on 2022-11-19 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20221114_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userexpertise',
            name='type',
        ),
        migrations.AddField(
            model_name='userexpertise',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='users.Expertise'),
        ),
    ]
