# Generated by Django 2.2.28 on 2022-11-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20221119_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexpertise',
            name='expertise',
        ),
        migrations.AddField(
            model_name='userexpertise',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
