# Generated by Django 2.2.28 on 2022-11-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20221119_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpertise',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.Profile'),
        ),
    ]
