version: "3"
services:
  web:
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:12
  redis:
    image: redis:5
  celery:
    build:
      context: .
    user: django
    command: celery -A growtal_35169 worker --beat --scheduler django --loglevel=info
    depends_on:
      - web
      - postgres
      - redis