version: "3"
services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:${PORT}"
  postgres:
    environment:
      POSTGRES_PASSWORD: <postgres_pwd>
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
    user: django
    command: celery -A growtal_35169 worker --beat --scheduler django --loglevel=info
    depends_on:
      - web
      - postgres
      - redis
volumes: 
  postgres-data:

