# Generated by Django 2.2.28 on 2022-10-07 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreedEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('expert_rate', models.PositiveIntegerField()),
                ('business_rate', models.PositiveIntegerField()),
                ('rate_per_bill', models.PositiveIntegerField()),
                ('agreement_start_date', models.DateField()),
                ('agreement_end_date', models.DateField()),
                ('description', models.TextField()),
                ('end', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreed_business', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreed_expert', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
