# Generated by Django 2.2.28 on 2022-10-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_agreedengagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreedengagement',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
