# Generated by Django 2.2.28 on 2022-10-24 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_admin', '0003_agreedengagement_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndingEngagementRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_call', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('agreed_engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_agreed_engagement', to='site_admin.AgreedEngagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_engagement_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
