# Generated by Django 2.2.28 on 2022-11-11 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_admin', '0005_agreedengagement_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreedengagement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_engagement_create', to=settings.AUTH_USER_MODEL),
        ),
    ]
