# Generated by Django 2.2.28 on 2022-12-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0006_agreedengagement_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreedengagement',
            name='agreement_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
