# Generated by Django 2.2.28 on 2022-12-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0007_auto_20221228_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreedengagement',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
