# Generated by Django 2.2.28 on 2022-09-27 12:25

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0002_notification_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
