# Generated by Django 2.2.28 on 2022-11-02 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push_notification', '0003_auto_20220927_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('notification_type', models.CharField(choices=[('Send_Now', 'Send_Now'), ('Scheduled', 'Scheduled')], max_length=10)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('experts', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_push_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
