# Generated by Django 2.2.28 on 2022-11-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0004_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='expert_q',
            field=models.CharField(blank=True, choices=[('All Expert', 'All Expert'), ('Selected Experts', 'Selected Experts')], max_length=255, null=True),
        ),
    ]
