# Generated by Django 2.2.28 on 2022-11-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0005_pushnotification_expert_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='expert_q',
            field=models.CharField(blank=True, choices=[('All Expert', 'All Expert'), ('All Business', 'All Business'), ('Selected User', 'Selected User')], max_length=255, null=True),
        ),
    ]
