# Generated by Django 2.2.28 on 2022-08-18 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_area', models.CharField(max_length=50)),
                ('digital_marketing', models.CharField(max_length=50)),
                ('additional_info', models.TextField(verbose_name=500)),
                ('commitment', models.IntegerField()),
                ('ended', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('engagements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='dashboard.Engagements')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
