# Generated by Django 2.2.28 on 2022-08-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_engagements_timelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refer',
            name='application_link',
        ),
        migrations.AddField(
            model_name='refer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
