# Generated by Django 2.2.28 on 2022-10-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220823_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagements',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engagements',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
