# Generated by Django 2.2.28 on 2022-10-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20221006_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagements',
            name='digital_marketing',
        ),
    ]
