# Generated by Django 2.2.28 on 2022-10-11 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_agreedengagement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_remove_engagements_digital_marketing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='engagements',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='user',
        ),
        migrations.AddField(
            model_name='timelog',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='site_admin.AgreedEngagement'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_engagement', to=settings.AUTH_USER_MODEL),
        ),
    ]
