# Generated by Django 2.2.28 on 2022-10-12 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_upsell'),
    ]

    operations = [
        migrations.AddField(
            model_name='upsell',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upsell_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upsell',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
