# Generated by Django 2.2.28 on 2022-10-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_education_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='resources',
            name='url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
