# Generated by Django 2.2.28 on 2022-10-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20221019_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='refer',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
