# Generated by Django 2.2.28 on 2022-10-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_billingperiods'),
        ('dashboard', '0011_refer_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelog_period', to='home.BillingPeriods'),
        ),
    ]
