# Generated by Django 2.2.28 on 2022-10-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_timelog_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='benefits/')),
                ('url', models.URLField(default='', max_length=500)),
            ],
        ),
    ]
