# Generated by Django 2.2.28 on 2022-11-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='content',
            field=models.CharField(blank=True, choices=[('EDUCATION CENTER', 'EDUCATION CENTER'), ('BENEFITS', 'BENEFITS'), ('RESOURCES', 'RESOURCES')], max_length=255, null=True),
        ),
    ]
