# Generated by Django 2.2.28 on 2022-11-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_resources_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='time_log',
            field=models.BooleanField(default=True),
        ),
    ]
