# Generated by Django 2.2.28 on 2022-11-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_timelog_time_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
