# Generated by Django 2.2.28 on 2022-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_resources_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='refer',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
