# Generated by Django 2.2.28 on 2022-11-10 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_refer_web_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
