# Generated by Django 2.2.28 on 2022-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20221110_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refer',
            name='web_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
