# Generated by Django 2.2.28 on 2022-08-19 15:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220801_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', ckeditor.fields.RichTextField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Feedback')),
            ],
        ),
    ]
