# Generated by Django 2.2.28 on 2022-10-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_billingperiods'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingperiods',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
