# Generated by Django 2.2.28 on 2022-10-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_billingperiods_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingperiods',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
