# Generated by Django 2.2.28 on 2022-11-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='app',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='email',
            field=models.BooleanField(),
        ),
    ]
