# Generated by Django 2.2.28 on 2022-11-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20221113_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='app',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='email',
            field=models.BooleanField(default=True),
        ),
    ]
