# Generated by Django 2.2.28 on 2022-11-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20221113_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_reply',
            field=models.BooleanField(default=False),
        ),
    ]
